### ISSUE TITLE
[JSCompiler] Executing Command Compile

### ISSUE THREAD

**Issue by mblais** [daPhyre/brackets-jscompiler#19]
Sorry, not much helpful info...
```
main.js:34 [JSCompiler] Executing Command Compile
uglifyjs.js:1 Uncaught Unexpected token: name (clone) (line: 22, col: 8, pos: 556)

Error
    at new M (file:///C:/Users/matt/AppData/Roaming/Brackets/extensions/user/ktayfer.jscompiler/UglifyJS/uglifyjs.js:1:3812)
    at N (file:///C:/Users/matt/AppData/Roaming/Brackets/extensions/user/ktayfer.jscompiler/UglifyJS/uglifyjs.js:1:3857)
    at u (file:///C:/Users/matt/AppData/Roaming/Brackets/extensions/user/ktayfer.jscompiler/UglifyJS/uglifyjs.js:1:8657)
    at s (file:///C:/Users/matt/AppData/Roaming/Brackets/extensions/user/ktayfer.jscompiler/UglifyJS/uglifyjs.js:1:8747)
    at f (file:///C:/Users/matt/AppData/Roaming/Brackets/extensions/user/ktayfer.jscompiler/UglifyJS/uglifyjs.js:1:8800)
    at h (file:///C:/Users/matt/AppData/Roaming/Brackets/extensions/user/ktayfer.jscompiler/UglifyJS/uglifyjs.js:1:9118)
    at b (file:///C:/Users/matt/AppData/Roaming/Brackets/extensions/user/ktayfer.jscompiler/UglifyJS/uglifyjs.js:1:9774)
    at file:///C:/Users/matt/AppData/Roaming/Brackets/extensions/user/ktayfer.jscompiler/UglifyJS/uglifyjs.js:1:13452
    at file:///C:/Users/matt/AppData/Roaming/Brackets/extensions/user/ktayfer.jscompiler/UglifyJS/uglifyjs.js:1:9219
    at F (file:///C:/Users/matt/AppData/Roaming/Brackets/extensions/user/ktayfer.jscompiler/UglifyJS/uglifyjs.js:1:10748)
```

Here is my .brackets.json :
```{
    "jscompiler": {
        "outputs": [
            {
                "inputs": [
                    "js/seedrandom.js",
                    "js/misc.js",
                    "js/MoUtils.js",
                    "js/undo.js",
                    "js/storage.js",
                    "js/widgets.js",
                    "js/settings.js",
                    "js/MoMess.js"
                ],
                "output": "all.min.js",
                "generateMap": false,
                "mangle": true,
                "isolate": false
            }
        ]
    }
}```

**Comment by daPhyre** [comment]
Can you test your code online at this site and see if it throws more light on the problem?

https://jscompress.com/

**Comment by mblais** [comment]
Sorry, I'm bailing on Brackets - too many weird issues like this.
